---
- name: get peco
  get_url:
    url: https://github.com/peco/peco/releases/download/v0.5.3/peco_linux_amd64.tar.gz
    dest: /tmp/peco_linux_amd64.tar.gz

- name: peco_linux_amd64 unarchived
  unarchive:
    src: /tmp/peco_linux_amd64.tar.gz
    dest: /tmp

- name: copy peco to /usr/local/bin
  copy:
    src: /tmp/peco_linux_amd64/peco
    dest: /usr/local/bin/peco
    mode: 0755
    owner: root
    group: root
