---
- name: get peco
  get_url:
    url: https://github.com/peco/peco/releases/download/v0.5.3/peco_linux_amd64.tar.gz
    dest: /tmp/peco_linux_amd64.tar.gz

- name: delete /tmp/peco_linux_amd64
  file:
    path: /tmp/peco_linux_amd64
    state: absent

- name: tar peco_linux_amd64
  command: tar zxvf /tmp/peco_linux_amd64.tar.gz
  args:
    chdir: /tmp

- name: copy peco to /usr/local/bin
  copy:
    src: /tmp/peco_linux_amd64/peco
    dest: /usr/local/bin/peco
    mode: 0755
    owner: root
    group: root
