---
- name: Development Tools installed
  ansible.builtin.package:
    name: "@Development Tools"
    state: present

- name: libraries installed
  ansible.builtin.package:
    name:
      - yum-utils
      - libcurl
      - libcurl-devel
      - jq
      - tree
    state: latest

- name: libraries installed (CentOS/RHEL 7 or earlier)
  when: ansible_distribution_major_version is version('7', '<=')
  ansible.builtin.package:
    name:
      - python2-pip
    state: latest

- name: libraries installed (CentOS/RHEL 8 or later)
  when: ansible_distribution_major_version is version('8', '>=')
  ansible.builtin.package:
    name:
      - python3-pip
    state: latest
