---
- name: stat custom httpd.conf.centos7.j2
  stat:
    path: /vagrant/config/httpd.conf.centos7.j2
  register: is_custom_httpd_conf_centos7

- name: custom httpd.conf changed
  template:
    src: /vagrant/config/httpd.conf.centos7.j2
    dest: /etc/httpd/conf/httpd.conf
  notify: httpd restarted
  when: is_custom_httpd_conf_centos7.stat.exists

- name: httpd.conf changed
  template:
    src: httpd.conf.centos7.j2
    dest: /etc/httpd/conf/httpd.conf
  notify: httpd restarted
  when: not is_custom_httpd_conf_centos7.stat.exists

- name: stat custom httpd.www.conf.centos7.j2
  stat:
    path: /vagrant/config/httpd.www.conf.centos7.j2
  register: is_custom_www_conf_centos7

- name: custom www.conf changed
  template:
    src: /vagrant/config/httpd.www.conf.centos7.j2
    dest: /etc/httpd/conf.d/www.conf
  notify: httpd restarted
  when: is_custom_www_conf_centos7.stat.exists

- name: www.conf changed
  template:
    src: httpd.www.conf.centos7.j2
    dest: /etc/httpd/conf.d/www.conf
  notify: httpd restarted
  when: not is_custom_www_conf_centos7.stat.exists

- name: http2.conf changed
  template:
    src: httpd.00-http2.conf.j2
    dest: /etc/httpd/conf.modules.d/00-http2.conf
  notify: httpd restarted

- block:
  - name: disables httpd module mpm_event
    replace:
      dest: /etc/httpd/conf.modules.d/00-mpm.conf
      regexp: "LoadModule mpm_event_module modules/mod_mpm_event.so"
      replace: "#LoadModule mpm_event_module modules/mod_mpm_event.so"
    notify: httpd restarted

  - name: enables httpd module mpm_prefork
    replace:
      dest: /etc/httpd/conf.modules.d/00-mpm.conf
      regexp: "#LoadModule mpm_prefork_module modules/mod_mpm_prefork.so"
      replace: "LoadModule mpm_prefork_module modules/mod_mpm_prefork.so"
    notify: httpd restarted
  when: apache_mpm == 'prefork'

- block:
  - name: disables httpd module mpm_prefork
    replace:
      dest: /etc/httpd/conf.modules.d/00-mpm.conf
      regexp: "LoadModule mpm_prefork_module modules/mod_mpm_prefork.so"
      replace: "#LoadModule mpm_prefork_module modules/mod_mpm_prefork.so"
    notify: httpd restarted

  - name: enables httpd module mpm_event
    replace:
      dest: /etc/httpd/conf.modules.d/00-mpm.conf
      regexp: "#LoadModule mpm_event_module modules/mod_mpm_event.so"
      replace: "LoadModule mpm_event_module modules/mod_mpm_event.so"
    notify: httpd restarted
  when: apache_mpm == 'event'
