---
- name: httpd installed
  package:
    name:
      - httpd24u
      - httpd24u-devel
    state: latest

- name: mod_ssl installed
  package:
    name: httpd24u-mod_ssl
    state: latest
  when: ssl

- name: stat custom httpd.conf.centos7.j2
  stat:
    path: /vagrant/config/httpd.conf.centos7.j2
  register: is_custom_httpd_conf_centos7

- name: custom httpd.conf changed
  template:
    src: /vagrant/config/httpd.conf.centos7.j2
    dest: /etc/httpd/conf/httpd.conf
    mode: 0644
  notify: httpd restarted
  when: is_custom_httpd_conf_centos7.stat.exists

- name: httpd.conf changed
  template:
    src: httpd.conf.centos7.j2
    dest: /etc/httpd/conf/httpd.conf
    mode: 0644
  notify: httpd restarted
  when: not is_custom_httpd_conf_centos7.stat.exists

- name: stat custom httpd.www.conf.centos7.j2
  stat:
    path: /vagrant/config/httpd.www.conf.centos7.j2
  register: is_custom_www_conf_centos7

- name: custom www.conf changed
  template:
    src: /vagrant/config/httpd.www.conf.centos7.j2
    dest: /etc/httpd/conf.d/www.conf
    mode: 0644
  notify: httpd restarted
  when: is_custom_www_conf_centos7.stat.exists

- name: www.conf changed
  template:
    src: httpd.www.conf.centos7.j2
    dest: /etc/httpd/conf.d/www.conf
    mode: 0644
  notify: httpd restarted
  when: not is_custom_www_conf_centos7.stat.exists

- name: http2.conf changed
  template:
    src: httpd.00-http2.conf.j2
    dest: /etc/httpd/conf.modules.d/00-http2.conf
    mode: 0644
  notify: httpd restarted

- name: enables httpd module mpm_prefork
  block:
  - name: disables httpd module mpm_event
    replace:
      dest: /etc/httpd/conf.modules.d/00-mpm.conf
      regexp: "^LoadModule mpm_event_module modules/mod_mpm_event.so\n"
      replace: "#LoadModule mpm_event_module modules/mod_mpm_event.so\n"
    notify: httpd restarted

  - name: enables httpd module mpm_prefork
    replace:
      dest: /etc/httpd/conf.modules.d/00-mpm.conf
      regexp: "^#LoadModule mpm_prefork_module modules/mod_mpm_prefork.so\n"
      replace: "LoadModule mpm_prefork_module modules/mod_mpm_prefork.so\n"
    notify: httpd restarted
  when: apache_mpm == 'prefork'

- name: enables httpd module mpm_event
  block:
  - name: disables httpd module mpm_prefork
    replace:
      dest: /etc/httpd/conf.modules.d/00-mpm.conf
      regexp: "^LoadModule mpm_prefork_module modules/mod_mpm_prefork.so\n"
      replace: "#LoadModule mpm_prefork_module modules/mod_mpm_prefork.so\n"
    notify: httpd restarted

  - name: enables httpd module mpm_event
    replace:
      dest: /etc/httpd/conf.modules.d/00-mpm.conf
      regexp: "^#LoadModule mpm_event_module modules/mod_mpm_event.so\n"
      replace: "LoadModule mpm_event_module modules/mod_mpm_event.so\n"
    notify: httpd restarted
  when: apache_mpm == 'event'
