---
- name: httpd installed
  package:
    name: "{{ item }}"
    state: latest
  with_items:
      - httpd
      - httpd-devel

- name: include task (CentOS/RHEL 6)
  include: centos6.yml
  when: 
    - ansible_os_family == 'RedHat'
    - ansible_distribution_major_version|int == 6

- name: include task (CentOS/RHEL 7)
  include: centos7.yml
  when:
    - ansible_os_family == 'RedHat'
    - ansible_distribution_major_version|int == 7

- name: mod_ssl installed
  package:
    name: mod_ssl
    state: latest
  when: ssl == true

- name: stat ssl.conf
  stat:
    path: /etc/httpd/conf.d/ssl.conf
  register: is_ssl_conf
  when: ssl == true

- name: delete ssl.conf
  file:
    path: /etc/httpd/conf.d/ssl.conf
    state: absent
  notify: httpd restarted
  when:
    - ssl == true
    - is_ssl_conf.stat.exists

- name: httpd enabled
  service:
    name: httpd
    enabled: yes
  notify: httpd restarted
