---
- name: include task (CentOS/RHEL)
  ansible.builtin.include_tasks: "{{ ansible_distribution }}{{ ansible_distribution_major_version }}.yml"

- name: stat ssl.conf
  when: ssl
  ansible.builtin.stat:
    path: /etc/httpd/conf.d/ssl.conf
  register: is_ssl_conf

- name: delete ssl.conf
  when:
    - ssl
    - is_ssl_conf.stat.exists
  ansible.builtin.file:
    path: /etc/httpd/conf.d/ssl.conf
    state: absent
  notify: httpd restarted

- name: httpd enabled
  ansible.builtin.service:
    name: httpd
    enabled: yes
  notify: httpd restarted
