---
- name: include task (CentOS/RHEL)
  include_tasks: "{{ ansible_distribution }}{{ ansible_distribution_major_version }}.yml"

- name: stat ssl.conf
  stat:
    path: /etc/httpd/conf.d/ssl.conf
  register: is_ssl_conf
  when: ssl

- name: delete ssl.conf
  file:
    path: /etc/httpd/conf.d/ssl.conf
    state: absent
  notify: httpd restarted
  when:
    - ssl
    - is_ssl_conf.stat.exists

- name: httpd enabled
  service:
    name: httpd
    enabled: yes
  notify: httpd restarted
