---
- name: "VAW (Vagrant Ansible WordPress) v0.5.2"
  hosts: localhost
  remote_user: vagrant
  become: yes
  connection: local

  roles:
    - { role: before-command,      tags: [before-command] }
    - { role: common,              tags: [common] }
    - { role: develop-tools,       tags: [develop-tools] }
    - { role: git,                 tags: [git] }
    - { role: mysql,               tags: [mysql],                when: "database == 'mysql'" }
    - { role: mariadb,             tags: [mariadb],              when: "database == 'mariadb'" }
    - { role: percona,             tags: [percona],              when: "database == 'percona'" }
    - { role: openssl,             tags: [openssl],              when: "ssl_wp_admin == true" }
    - { role: apache,              tags: [apache],               when: "server == 'apache'" }
    - { role: nginx,               tags: [nginx],                when: "server == 'nginx'" }
    - { role: phpenv,              tags: [phpenv] }
    - { role: h2o,                 tags: [h2o],                  when: "server == 'h2o'" }
    - { role: hhvm,                tags: [hhvm],                 when: "fastcgi == 'hhvm'" }
    - { role: wp-cli,              tags: [wp-cli] }
    - { role: wordpress,           tags: [wordpress, sync-dir] }
    - { role: rbenv,               tags: [rbenv],                when: "develop_tools == true or deploy_tools == true" }
    - { role: nodenv,              tags: [nodenv],               when: "develop_tools == true" }
    - { role: wordpress-develop,   tags: [wordpress-develop],    when: "develop_tools == true" }
    - { role: wordpress-deploy,    tags: [wordpress-deploy],     when: "deploy_tools == true" }
    - { role: after-command,       tags: [after-command] }
