---
- name: WordPress db check
  command: wp --path={{ WP_PATH }} db check
  become: yes
  become_user: vagrant
  register: db_check
  failed_when: false
  changed_when: false

- name: database drop
  command: wp --path={{ WP_PATH }} db drop --yes
  become: yes
  become_user: vagrant
  when: db_check.rc == 0

- name: remove MySQL user for WordPress
  mysql_user:
    name: "{{ db_user }}"
    host_all: yes
    state: absent
    login_user: root
    login_password: "{{ db_root_password }}"
    login_unix_socket: /tmp/mysql.sock
  when: ansible_distribution == 'Debian'

- name: Setup MySQL user for WordPress
  mysql_user:
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    host: "{{ item }}"
    priv: "{{ db_name }}.*:ALL"
    state: present
    login_user: root
    login_password: "{{ db_root_password }}"
    login_unix_socket: /tmp/mysql.sock
  with_items:
    - localhost
    - 127.0.0.1
    - ::1
  no_log: True

- name: stat WP_PATH
  stat:
    path: "{{ WP_PATH }}"
  register: is_wordpress_path

- name: mkdir wordpress_path
  file:
    path: "{{ WP_PATH }}"
    state: directory
    recurse: yes
  when: not is_wordpress_path.stat.exists

- name: stat site_path
  stat:
    path: "{{ DOCUMENT_ROOT }}{{ wp_site_path }}"
  register: is_site_path

- name: mkdir site_path
  file:
    path: "{{ DOCUMENT_ROOT }}{{ wp_site_path }}"
    state: directory
    recurse: yes
  when: not is_site_path.stat.exists

- name: WordPress latest installed
  command: wp --path={{ WP_PATH }} core download --locale={{ lang }} --force
  become: yes
  become_user: vagrant
  when: version == "latest"

- name: WordPress version installed
  command: wp --path={{ WP_PATH }} core download --locale={{ lang }} --version={{ version }} --force
  become: yes
  become_user: vagrant
  when: version != "latest"

- name: stat wp-config.php
  stat:
    path: "{{ WP_PATH }}/wp-config.php"
  register: is_old_wp_config

- name: delete WordPress config
  file:
    path: "{{ WP_PATH }}/wp-config.php"
    state: absent
  when: is_old_wp_config.stat.exists

- name: stat wp-config.php
  stat:
    path: "{{ WP_PATH }}/wp-config.php"
  register: is_old_wp_config

- name: WordPress config
  command: wp --path={{ WP_PATH }} core config --dbhost={{ db_host }} --dbname={{ db_name }} --dbuser={{ db_user }} --dbpass={{ db_password }} --locale={{ lang }} --dbprefix={{ db_prefix }} --dbcharset={{ db_charset }} --dbcollate={{ db_collate }}
  become: yes
  become_user: vagrant
  when: not is_old_wp_config.stat.exists

- name: WordPress db check
  command: wp --path={{ WP_PATH }} db check
  become: yes
  become_user: vagrant
  register: db_check
  failed_when: false
  changed_when: false

- name: WordPress db create
  command: wp --path={{ WP_PATH }} db create
  become: yes
  become_user: vagrant
  when: db_check.rc != 0

- name: WordPress core install
  command: wp --path={{ WP_PATH }} core install --url={{ WP_URL }} --title='{{ title }}' --admin_user={{ admin_user }} --admin_password={{ admin_password }} --admin_email={{ admin_email }}
  become: yes
  become_user: vagrant
  when: not multisite

- name: WordPress multisite core install
  command: wp --path={{ WP_PATH }} core multisite-install --url={{ WP_URL }} --title='{{ title }}' --admin_user={{ admin_user }} --admin_password={{ admin_password }} --admin_email={{ admin_email }}
  become: yes
  become_user: vagrant
  when: multisite

- name: .htaccess changed
  template:
    src: wordpress.multisite.htaccess.j2
    dest: "{{ WP_PATH }}/.htaccess"
    mode: 0644
  when:
    - multisite
    - server == "apache"

- name: set WP_DEBUG in wp-config.php
  replace:
    dest: "{{ WP_PATH }}/wp-config.php"
    regexp: '\n/\* That'
    replace: "define( 'WP_DEBUG', {{ WP_DEBUG }} );\n\n/* That"

- name: set SAVEQUERIES in wp-config.php
  replace:
    dest: "{{ WP_PATH }}/wp-config.php"
    regexp: '\n/\* That'
    replace: "define( 'SAVEQUERIES', {{ SAVEQUERIES }} );\n\n/* That"

- name: set SSL in wp-config.php
  replace:
    dest: "{{ WP_PATH }}/wp-config.php"
    regexp: '\n/\* That'
    replace: "// define( 'FORCE_SSL_LOGIN', true );\ndefine( 'FORCE_SSL_ADMIN', true );\n\n/* That"
  when: ssl

- name: subdirectory install
  block:
  - name: change wp option for subdirectory install
    command: wp --path={{ WP_PATH }} option update siteurl 'http://{{ HOSTNAME }}{{ wp_dir }}'
    become: yes
    become_user: vagrant

  - name: copy index.php for subdirectory install
    copy:
      src: "{{ DOCUMENT_ROOT }}{{ wp_dir }}/index.php"
      dest: "{{ DOCUMENT_ROOT }}{{ wp_site_path }}/index.php"
      mode: 0644

  - name: change load path in index.php for subdirectory install
    replace:
      dest: "{{ DOCUMENT_ROOT }}{{ wp_site_path }}/index.php"
      regexp: "'/wp-blog-header.php'"
      replace: "'{{ wp_dir }}/wp-blog-header.php'"

  - name: copy .htaccess for subdirectory install
    copy:
      src: "{{ DOCUMENT_ROOT }}{{ wp_dir }}/.htaccess"
      dest: "{{ DOCUMENT_ROOT }}{{ wp_site_path }}/.htaccess"
      mode: 0644
    when:
      - multisite
      - server == "apache"
  when: wp_site_path != wp_dir

- name: themes install
  command: wp --path={{ WP_PATH }} theme install {{ item }}
  become: yes
  become_user: vagrant
  with_items:
    - "{{ themes | default([]) }}"
  when:
    - "themes"

- name: theme install and activate
  command: wp --path={{ WP_PATH }} theme install {{ activate_theme }} --activate
  become: yes
  become_user: vagrant
  when:
    - "activate_theme"

- name: plugin activate wp-multibyte-patch
  command: wp --path={{ WP_PATH }} plugin activate wp-multibyte-patch
  become: yes
  become_user: vagrant
  when: lang == "ja"

- name: plugins install and activate
  command: wp --path={{ WP_PATH }} plugin install {{ item }} --activate
  become: yes
  become_user: vagrant
  with_items:
    - "{{ activate_plugins | default([]) }}"
  when: "activate_plugins"

- name: plugins install
  command: wp --path={{ WP_PATH }} plugin install {{ item }}
  become: yes
  become_user: vagrant
  with_items:
    - "{{ plugins | default([]) }}"
  when: "plugins"
