---

- name: include install
  ansible.builtin.include_tasks: install.yml

- name: include import
  ansible.builtin.include_tasks: import.yml

- name: include options
  ansible.builtin.include_tasks: options.yml
