---
- name: stat before_provision.sh
  stat:
    path: /vagrant/command/before_provision.sh
  register: before_command

- name: before provision command
  command: /vagrant/command/before_provision.sh
  when: before_command.stat.exists

- name: sync-dir
  block:
  - name: stat before_provision.sh
    stat:
      path: /vagrant/command/before_provision.sh
    register: before_command

  - name: before provision command
    command: /vagrant/command/before_provision.sh
    when: before_command.stat.exists
  tags: sync-dir
