---
- name: stat before_provision.sh
  ansible.builtin.stat:
    path: /vagrant/command/before_provision.sh
  register: before_command

- name: before provision command
  when: before_command.stat.exists
  ansible.builtin.command: /vagrant/command/before_provision.sh

- name: sync-dir
  tags: sync-dir
  block:
  - name: stat before_provision.sh
    ansible.builtin.stat:
      path: /vagrant/command/before_provision.sh
    register: before_command

  - name: before provision command
    when: before_command.stat.exists
    ansible.builtin.command: /vagrant/command/before_provision.sh
