---
- name: CentOS
  when: ansible_distribution == 'CentOS'
  block:
  - name: MariaDB 10.11 repository added
    ansible.builtin.yum_repository:
      name: mariadb
      description: MariaDB 10.11 centos repository
      baseurl: "http://yum.mariadb.org/10.11/centos{{ ansible_distribution_major_version }}-amd64"
      gpgkey: https://yum.mariadb.org/RPM-GPG-KEY-MariaDB
      gpgcheck: yes

  - name: MariaDB installed (CentOS/RHEL 6 or 7)
    when: ansible_distribution_major_version is version('7', '<=')
    ansible.builtin.package:
      name:
        - MariaDB-server
        - MariaDB-client
        - MariaDB-shared
        - MariaDB-devel
        - MariaDB-common
        - MySQL-python
      state: latest

  - name: version 8 later
    when: ansible_distribution_major_version is version('8', '>=')
    block:
    - name: boost-program-options installed
      ansible.builtin.dnf:
        name: boost-program-options
        state: latest

    - name: it not been implemented yet.
      ansible.builtin.fail:
        msg: Not enough packages are available.

    - name: MariaDB 10.11 installed (CentOS/RHEL 8)
      ansible.builtin.dnf:
        name:
          - MariaDB-server
          - MariaDB-client
          - MariaDB-shared
          - MariaDB-devel
          - MariaDB-common
        disablerepo: AppStream
        state: latest

    - name: python3-PyMySQL installed (CentOS/RHEL 8)
      ansible.builtin.dnf:
        name:
          - python2-PyMySQL
          - python3-PyMySQL
        state: latest

- name: Ubuntu
  when: ansible_distribution == 'Ubuntu'
  block:
  - name: MariaDB apt_key installed (Ubuntu/xenial or later)
    when: ansible_distribution_major_version is version('16', '>=')
    ansible.builtin.apt_key:
      keyserver: keyserver.ubuntu.com
      id: "0xF1656F24C74CD1D8"

  - name: MariaDB apt_key installed (Ubuntu/trusty)
    when: ansible_distribution_major_version is version('14', '==')
    ansible.builtin.apt_key:
      keyserver: keyserver.ubuntu.com
      id: "0xcbcb082a1bb943db"

  - name: MariaDB 10.11 repository installed
    ansible.builtin.apt_repository:
      filename: MariaDB
      repo: 'deb [arch=amd64,i386,ppc64el] https://deb.mariadb.org/10.11/ubuntu {{ ansible_distribution_release }} main'

  - name: MariaDB 10.11 installed (Ubuntu)
    ansible.builtin.package:
      name:
        - mariadb-server
        - mariadb-client
        - mariadb-common
        - libmariadbd-dev
        - libmariadbclient18
      state: latest

- name: Debian
  when: ansible_distribution == 'Debian'
  block:
  - name: MariaDB apt_key installed (Debian/stretch or later)
    when: ansible_distribution_major_version is version('9', '>=')
    ansible.builtin.apt_key:
      keyserver: hkp://keyserver.ubuntu.com:80
      id: "0xF1656F24C74CD1D8"

  - name: MariaDB apt_key installed (Debian/jessie)
    when: ansible_distribution_major_version is version('8', '==')
    ansible.builtin.apt_key:
      keyserver: keyserver.ubuntu.com
      id: "0xcbcb082a1bb943db"

  - name: MariaDB 10.11 repository installed
    ansible.builtin.apt_repository:
      filename: MariaDB
      repo: 'deb [arch=amd64,i386] https://deb.mariadb.org/10.11/debian {{ ansible_distribution_release }} main'

  - name: MariaDB 10.11 installed (Debian)
    ansible.builtin.package:
      name:
        - mariadb-server
        - mariadb-client
        - mariadb-common
        - libmariadbd-dev
        - libmariadbclient18
      state: latest

- name: python-mysqldb installed
  when:
    - ansible_distribution == 'Ubuntu'
    - ansible_distribution_major_version is version('18', '<=')
  ansible.builtin.package:
    name: python-mysqldb
    state: latest

- name: python3-mysqldb installed
  when:
    - ansible_distribution == 'Ubuntu'
    - ansible_distribution_major_version is version('20', '>=')
  ansible.builtin.package:
    name: python3-mysqldb
    state: latest

- name: python3-mysqldb installed
  when: ansible_distribution == 'Debian'
  ansible.builtin.package:
    name: python3-mysqldb
    state: latest
