---
- name: check installed daemonize
  ansible.builtin.command: type daemonize
  register: daemonize_installed
  failed_when: false
  changed_when: false

- name: daemonize installed
  when: daemonize_installed.rc == 1
  block:
  - name: get daemonize archive
    ansible.builtin.get_url:
      url: https://github.com/bmc/daemonize/archive/release-1.7.8.zip
      dest: /tmp/daemonize-1.7.8.zip
      mode: "0755"

  - name: mkdir /tmp/daemonize
    ansible.builtin.file:
      path: /tmp/daemonize
      state: directory
      mode: "0755"

  - name: unarchive daemonize
    ansible.builtin.unarchive:
      src: /tmp/daemonize-1.7.8.zip
      dest: /tmp/daemonize

  - name: build daemonize
    ansible.builtin.command: "{{ item }}"
    args:
      chdir: /tmp/daemonize/daemonize-release-1.7.8
    with_items:
      - ./configure --prefix=/usr
      - make
      - make install
