---
- block:
  - name: mysql repository installed (CentOS/RHEL 6)
    yum:
      name: https://dev.mysql.com/get/mysql57-community-release-el6-9.noarch.rpm
    when: ansible_distribution_major_version|int == 6

  - name: mysql repository installed (CentOS/RHEL 7)
    yum:
      name: https://dev.mysql.com/get/mysql57-community-release-el7-9.noarch.rpm
    when: ansible_distribution_major_version|int == 7

  - name: yum-config disable mysql57-community
    command: yum-config-manager --disable mysql57-community

  - name: yum-config enable mysql56-community
    command: yum-config-manager --enable mysql56-community

  - name: mysql 5.6 installed (CentOS/RHEL)
    package:
      name: "{{ item }}"
      state: latest
    with_items:
      - mysql-community-server
      - mysql-community-client
      - mysql-community-common
      - mysql-community-devel
      - mysql-community-libs
      - mysql-utilities
      - MySQL-python
  when: ansible_os_family == 'RedHat'

- block:
  - name: set mysql-apt-config to mysql version 5.6
    debconf:
      name: mysql-apt-config
      question: "{{ item.question }}"
      value: "{{ item.value }}"
      vtype: "{{ item.vtype | default ('select') }}"
    with_items:
      - question: mysql-apt-config/select-server
        value: mysql-5.6
      - question: mysql-apt-config/select-tools
        value: Enabled

  - name: set mysql-apt-config to mysql version 5.7 (only xenial)
    debconf:
      name: mysql-apt-config
      question: "{{ item.question }}"
      value: "{{ item.value }}"
      vtype: "{{ item.vtype | default ('select') }}"
    with_items:
      - question: mysql-apt-config/select-server
        value: mysql-5.7
    when: ansible_distribution_release == 'xenial'

  - name: mysql-apt-config installed (Debian)
    apt:
      deb: https://dev.mysql.com/get/mysql-apt-config_0.8.10-1_all.deb

  - name: apt-get update
    command: apt-get update

  - name: mysql installed (Debian)
    package:
      name: "{{ item }}"
      state: latest
    with_items:
      - mysql-community-server
      - mysql-community-client
      - mysql-common
      - mysql-utilities
      - python-mysqldb
  when: ansible_os_family == 'Debian'
