---
- name: RedHat
  when: ansible_os_family == 'RedHat'
  block:
  - name: mysql repository installed (CentOS/RHEL 6)
    when: ansible_distribution_major_version is version('6', '==')
    ansible.builtin.yum:
      name: https://dev.mysql.com/get/mysql57-community-release-el6-9.noarch.rpm
      disable_gpg_check: yes

  - name: mysql repository installed (CentOS/RHEL 7)
    when: ansible_distribution_major_version is version('7', '==')
    ansible.builtin.yum:
      name: https://dev.mysql.com/get/mysql57-community-release-el7-9.noarch.rpm
      disable_gpg_check: yes

  - name: mysql repository installed (CentOS/RHEL 8)
    when: ansible_distribution_major_version is version('8', '==')
    ansible.builtin.yum:
      name: https://dev.mysql.com/get/mysql57-community-release-el7-9.noarch.rpm
      disable_gpg_check: yes

  - name: yum-config disable mysql57-community
    ansible.builtin.command: yum-config-manager --disable mysql57-community

  - name: yum-config enable mysql56-community
    ansible.builtin.command: yum-config-manager --enable mysql56-community

  - name: mysql 5.6 installed (CentOS/RHEL)
    ansible.builtin.package:
      name:
        - mysql-community-server
        - mysql-community-client
        - mysql-community-common
        - mysql-community-devel
        - mysql-community-libs
        - MySQL-python
      state: latest

- name: Debian
  when: ansible_os_family == 'Debian'
  block:
  - name: set mysql-apt-config to mysql version 5.6
    ansible.builtin.debconf:
      name: mysql-apt-config
      question: "{{ item.question }}"
      value: "{{ item.value }}"
      vtype: "{{ item.vtype | default('select') }}"
    with_items:
      - question: mysql-apt-config/select-server
        value: mysql-5.6
      - question: mysql-apt-config/select-tools
        value: Enabled

  - name: set mysql-apt-config to mysql version 5.7 (only focal)
    when: ansible_distribution_major_version is version('20', '==')
    ansible.builtin.debconf:
      name: mysql-apt-config
      question: "{{ item.question }}"
      value: "{{ item.value }}"
      vtype: "{{ item.vtype | default('select') }}"
    with_items:
      - question: mysql-apt-config/select-server
        value: mysql-5.7

  - name: set mysql-apt-config to mysql version 5.7 (only bionic)
    when: ansible_distribution_major_version is version('18', '==')
    ansible.builtin.debconf:
      name: mysql-apt-config
      question: "{{ item.question }}"
      value: "{{ item.value }}"
      vtype: "{{ item.vtype | default('select') }}"
    with_items:
      - question: mysql-apt-config/select-server
        value: mysql-5.7

  - name: set mysql-apt-config to mysql version 5.7 (only xenial)
    when: ansible_distribution_major_version is version('16', '==')
    ansible.builtin.debconf:
      name: mysql-apt-config
      question: "{{ item.question }}"
      value: "{{ item.value }}"
      vtype: "{{ item.vtype | default('select') }}"
    with_items:
      - question: mysql-apt-config/select-server
        value: mysql-5.7

  - name: mysql-apt-config installed (Debian)
    ansible.builtin.apt:
      deb: https://dev.mysql.com/get/mysql-apt-config_0.8.32-1_all.deb

  - name: apt-key update
    ansible.builtin.command: apt-key adv --keyserver pgp.mit.edu --recv-keys 5072E1F5

  - name: apt-get update
    ansible.builtin.apt:
      update_cache: yes

  - name: mysql installed (Debian)
    ansible.builtin.package:
      name:
        - mysql-community-server
        - mysql-community-client
        - mysql-common
      state: latest

- name: python-mysqldb installed
  when:
    - ansible_distribution == 'Ubuntu'
    - ansible_distribution_major_version is version('18', '<=')
  ansible.builtin.package:
    name: python-mysqldb
    state: latest

- name: python3-mysqldb installed
  when:
    - ansible_distribution == 'Ubuntu'
    - ansible_distribution_major_version is version('20', '>=')
  ansible.builtin.package:
    name: python3-mysqldb
    state: latest

- name: python-mysqldb installed
  when: ansible_distribution == 'Debian'
  ansible.builtin.package:
    name: python-mysqldb
    state: latest
