---
- name: git checkout nodenv
  git:
    repo: https://github.com/nodenv/nodenv.git
    dest: "{{ nodenv_dir }}"
    force: yes
  become: yes
  become_user: vagrant

- name: edit PATH nodenv on .bashrc_vaw
  lineinfile:
    dest: "{{ home_dir }}/.bashrc_vaw"
    line: "export PATH=$HOME/.nodenv/bin:$PATH"

- name: edit nodenv init on .bashrc_vaw
  lineinfile:
    dest: "{{ home_dir }}/.bashrc_vaw"
    line: "eval \"$(nodenv init -)\""

- name: git checkout node-build
  git:
    repo: https://github.com/nodenv/node-build.git
    dest: "{{ nodenv_dir }}/plugins/node-build"
    force: yes
  become: yes
  become_user: vagrant

- name: git checkout nodenv-default-packages
  git:
    repo: https://github.com/nodenv/nodenv-default-packages.git
    dest: "{{ nodenv_dir }}/plugins/nodenv-default-packages"
    force: yes
  become: yes
  become_user: vagrant

- name: stat default_node_packages
  stat:
    path: /vagrant/config/default-node-packages.j2
  register: is_default_node_packages

- name: nodenv-default-packages changed
  template:
    src: /vagrant/config/default-node-packages.j2
    dest: "{{ nodenv_dir }}/default-packages"
  become: yes
  become_user: vagrant
  when: is_default_node_packages.stat.exists

- name: nodejs installed via nodenv
  command: "{{ nodenv_dir }}/bin/nodenv install {{ node_version | default('6.9.1') }}"
  ignore_errors: yes
  become: yes
  become_user: vagrant

- name: nodenv rehash
  command: "{{ nodenv_dir }}/bin/nodenv rehash"
  become: yes
  become_user: vagrant

- name: nodenv global
  command: "{{ nodenv_dir }}/bin/nodenv global {{ node_version | default('6.9.1') }}"
  become: yes
  become_user: vagrant
