---
- name: yarn.repo repository added (CentOS/RHEL)
  when: ansible_os_family == 'RedHat'
  ansible.builtin.yum_repository:
    name: yarn
    description: Yarn Repository
    baseurl: https://dl.yarnpkg.com/rpm/
    gpgkey: https://dl.yarnpkg.com/rpm/pubkey.gpg
    enabled: yes
    gpgcheck: yes

- name: Debian
  when: ansible_os_family == 'Debian'
  block:
  - name: GPG key added (Debian)
    ansible.builtin.apt_key:
      url: https://dl.yarnpkg.com/debian/pubkey.gpg
      state: present

  - name: yarn repository installed (Debian)
    ansible.builtin.apt_repository:
      repo: "deb https://dl.yarnpkg.com/debian/ stable main"
      filename: yarn
      state: present

  - name: apt-get update
    ansible.builtin.apt:
      update_cache: yes

- name: yarn installed
  ansible.builtin.package:
    name: yarn
    state: latest
