---
- name: yarn.repo repository added (CentOS/RHEL)
  yum_repository:
    name: yarn
    description: Yarn Repository
    baseurl: https://dl.yarnpkg.com/rpm/
    gpgkey: https://dl.yarnpkg.com/rpm/pubkey.gpg
    enabled: yes
    gpgcheck: yes
  when: ansible_os_family == 'RedHat'

- name: Debian
  block:
  - name: GPG key added (Debian)
    apt_key:
      url: https://dl.yarnpkg.com/debian/pubkey.gpg
      state: present

  - name: yarn repository installed (Debian)
    apt_repository:
      repo: "deb https://dl.yarnpkg.com/debian/ stable main"
      filename: yarn
      state: present

  - name: apt-get update
    apt:
      update_cache: yes
  when: ansible_os_family == 'Debian'

- name: yarn installed
  package:
    name: yarn
    state: latest
