---
- name: RedHat version 7 early
  block:
  - name: older git remove
    package:
      name: git
      state: absent

  - name: git v2 or later installed
    package:
      name: git236
      state: latest
  when:
    - ansible_os_family == 'RedHat'
    - ansible_distribution_major_version is version('7', '<=')

- name: git installed
  package:
    name: git
    state: latest
  when: ansible_os_family == 'Debian'
