---
- name: RedHat version 7 early
  when:
    - ansible_os_family == 'RedHat'
    - ansible_distribution_major_version is version('7', '<=')
  block:
  - name: older git remove
    ansible.builtin.package:
      name: git
      state: absent

  - name: git v2 or later installed
    ansible.builtin.package:
      name: git236
      state: latest

- name: git installed
  when: ansible_os_family == 'Debian'
  ansible.builtin.package:
    name: git
    state: latest
