---
- name: firewalld stoped and disabled (CentOS/RHEL 7)
  ansible.builtin.service:
    name: firewalld
    state: stopped
    enabled: no

- name: chrony installed
  ansible.builtin.package:
    name: chrony

- name: chrony started and enabled
  ansible.builtin.service:
    name: chronyd
    state: restarted
    enabled: yes

- name: IUS repository installed (CentOS/RHEL 7)
  ansible.builtin.yum:
    name: https://repo.ius.io/ius-release-el7.rpm
    disable_gpg_check: yes
