---
- name: libselinux-python installed
  package:
    name: libselinux-python
    state: latest

- name: disable selinux
  selinux:
    state: disabled

- name: is_getenforce
  command: /usr/sbin/getenforce
  register: is_getenforce

- name: SELinux is turned off
  fail:
    msg: "SELinux is turned off. please run again, 'vagrant reload --provision'"
  when: is_getenforce.stdout == 'Enforcing'

- name: iptables stoped and disabled
  service:
    name: iptables
    state: stopped
    enabled: no

- name: ntp installed
  package:
    name: ntp

- name: ntp started and enabled
  service:
    name: ntpd
    state: restarted
    enabled: yes

- name: IUS repository installed (CentOS/RHEL 6)
  yum:
    name: https://dl.iuscommunity.org/pub/ius/stable/CentOS/6/x86_64/ius-release-1.0-15.ius.centos6.noarch.rpm
