---
- name: iptables stoped and disabled
  ansible.builtin.service:
    name: iptables
    state: stopped
    enabled: no

- name: ntp installed
  ansible.builtin.package:
    name: ntp

- name: ntp started and enabled
  ansible.builtin.service:
    name: ntpd
    state: restarted
    enabled: yes

- name: IUS repository installed (CentOS/RHEL 6)
  ansible.builtin.yum:
    name: https://repo.ius.io/ius-release-el6.rpm
    disable_gpg_check: yes
