---
- name: firewalld stoped and disabled (CentOS/RHEL 8)
  service:
    name: firewalld
    state: stopped
    enabled: no

- name: chrony installed
  package:
    name: chrony

- name: chrony started and enabled
  service:
    name: chronyd
    state: restarted
    enabled: yes

- name: dnf-plugins-core installed
  dnf:
    name: dnf-plugins-core
    state: latest

- name: stat PowerTools.repo
  stat:
    path: '/etc/yum.repos.d/CentOS-Linux-PowerTools.repo'
  register: is_powertools_repo

- name: powertools enabled (CentOS/RHEL 8)
  command: dnf config-manager --set-enabled powertools
  when: is_docker_ce_repo.stat.exists
