---
- name: all packages updated
  when:
    - ansible_distribution == 'Ubuntu'
  ansible.builtin.apt:
    name: '*'
    state: latest

- name: sysv-rc-conf installed
  when: ansible_distribution_major_version is version('14', '==')
  ansible.builtin.package:
    name: sysv-rc-conf
    state: latest

- name: apt-transport-https installed
  when: ansible_distribution == 'Debian'
  ansible.builtin.package:
    name: apt-transport-https
    state: latest

- name: ntp installed
  ansible.builtin.package:
    name: ntp
    state: latest

- name: ntp started and enabled
  ansible.builtin.service:
    name: ntp
    state: restarted
    enabled: yes
