---
- name: edit PATH on .bashrc_vaw
  lineinfile:
    dest: "{{ home_dir }}/.bashrc_vaw"
    line: "export PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/sbin:$PATH"
    create: yes
  become: yes
  become_user: vagrant

- name: edit PATH on .bashrc
  lineinfile:
    dest: "{{ home_dir }}/.bashrc"
    line: "if [ -f ~/.bashrc_vaw ]; then\n        . ~/.bashrc_vaw\nfi"
    create: yes
  become: yes
  become_user: vagrant
  when: ansible_os_family == 'RedHat'

- name: edit PATH on .profile
  lineinfile:
    dest: "{{ home_dir }}/.profile"
    line: "if [ -f ~/.bashrc_vaw ]; then\n        . ~/.bashrc_vaw\nfi"
    create: yes
  become: yes
  become_user: vagrant
  when: ansible_os_family == 'Debian'
