---
- name: include task (CentOS/RHEL)
  include_tasks: selinux.yml

- name: all packages updated
  yum:
    name: '*'
    state: latest

- name: include task (CentOS/RHEL)
  include_tasks: "{{ ansible_distribution }}{{ ansible_distribution_major_version }}.yml"
