---
- name: include task (CentOS/RHEL)
  ansible.builtin.include_tasks: selinux.yml

- name: all packages updated
  ansible.builtin.yum:
    name: '*'
    state: latest

- name: include task (CentOS/RHEL)
  ansible.builtin.include_tasks: "{{ ansible_distribution }}{{ ansible_distribution_major_version }}.yml"
