---
- name: libselinux-python installed
  ansible.builtin.package:
    name: libselinux-python
    state: latest

- name: disable selinux
  ansible.posix.selinux:
    state: disabled
  register: is_selinux

- name: checking SELinux is turned off
  when: is_selinux.state == 'enforcing'
  ansible.builtin.fail:
    msg: "SELinux is turned off. please run again, 'vagrant reload --provision'"
