---
- name: libselinux-python installed
  package:
    name: libselinux-python
    state: latest

- name: disable selinux
  selinux:
    state: disabled
  register: is_selinux

- name: checking SELinux is turned off
  fail:
    msg: "SELinux is turned off. please run again, 'vagrant reload --provision'"
  when: is_selinux.state == 'enforcing'
