---
- name: deploy tools installed
  package:
    name:
      - sshpass
      - lftp
      - python-devel
      - python-setuptools
      - python-pip
    state: present

- name: gem libraries globally installed
  gem:
    name: "{{ item }}"
    executable: "{{ rbenv_dir }}/shims/gem"
    user_install: false
  with_items:
    - net-sftp
    - double-bag-ftps
    - dandelion
    - wordmove
  become: yes
  become_user: vagrant

- name: Deployer installed
  command: "{{ phpenv_dir }}/shims/composer global require 'deployer/deployer'"
  become: yes
  become_user: vagrant

- name: git checkout git-ftp
  git:
    repo: https://github.com/git-ftp/git-ftp.git
    dest: /tmp/git-ftp
    force: yes
  become: yes
  become_user: vagrant

- name: git-ftp installed
  command: make install
  args:
    chdir: /tmp/git-ftp
