---
- name: deploy tools installed
  package:
    name:
      - sshpass
      - lftp
      - python-devel
      - python-setuptools
      - python-pip
    state: present

- name: gem libraries globally installed
  gem:
    name: "{{ item }}"
    executable: "{{ rbenv_dir }}/shims/gem"
    user_install: false
  with_items:
    - net-sftp
    - double-bag-ftps
    - dandelion
    - wordmove
  become: yes
  become_user: vagrant
