---
- name: deploy tools installed
  package:
    name: "{{ item }}"
  with_items:
    - sshpass
    - lftp
    - python-devel
    - python-setuptools
    - python-pip

- name: gem libraries installed
  command: gem install {{ item }}
  # gem:
  #   name: "{{ item }}"
  #   state: latest
  with_items:
    - capistrano
    - capistrano_colors
    - capistrano-ext
    - railsless-deploy
    - net-sftp
    - double-bag-ftps
    - dandelion
    - wordmove
  become: yes
  become_user: vagrant
  
- name: pycrypto uninstalled
  pip:
    name: pycrypto
    state: absent
  ignore_errors: yes

- name: fabric installed
  pip:
    name: "{{ item.name }}"
    version: "{{ item.version }}"
  with_items:
    - { name: 'pycrypto', version: '2.6.1' }
    - { name: 'paramiko', version: '1.11.6' }
    - { name: 'fabric', version: '1.10.1' }
