---
- name: deploy tools installed
  package:
    name: "{{ item }}"
  with_items:
    - sshpass
    - lftp
    - python-devel
    - python-setuptools
    - python-pip

- name: gem libraries installed
  gem:
    name: "{{ item }}"
    executable: "{{ rbenv_dir }}/shims/gem"
  with_items:
    - net-sftp
    - double-bag-ftps
    - dandelion
    - wordmove
  become: yes
  become_user: vagrant
