---
- name: build environment
  package:
    name:
      - gcc
      - cmake
    state: latest

- name: build environment (CentOS/RHEL)
  package:
    name:
      - openssl-devel
      - libyaml-devel
      - readline-devel
      - zlib-devel
    state: latest
  when: ansible_os_family == 'RedHat'

- name: build environment (Debian)
  package:
    name:
      - libssl-dev
      - libyaml-dev
      - libreadline-dev
      - zlib1g-dev
    state: latest
  when: ansible_os_family == 'Debian'
