name: Ansible lint

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: Install Ansible and Ansible Lint
        run: |
          python -m pip install --upgrade pip
          pip install ansible ansible-lint

      - name: Run checking syntax
        run: ansible-playbook --syntax-check -i hosts/local site.yml

      - name: Run ansible lint
        run: ansible-lint site.yml
